package com.logex.demo.config;

public final class Utils {
    private static final String[] CITIES = {
            "Abbottabad",
            "Ahmadpur East",
            "Ahmed Nager Chatha",
            "Ali Khan Abad",
            "Alipur",
            "Arifwala",
            "Astore",
            "Attock",
            "Benazirabad",
            "Bhera",
            "Bhalwal",
            "Bahawalnagar",
            "Bahawalpur",
            "Bhakkar",
            "Bhimber",
            "Burewala",
            "Chenab Nagar",
            "Chillianwala",
            "Choa Saidanshah",
            "Chakwal",
            "Chak Jhumra",
            "Chichawatni",
            "Chiniot",
            "Chishtian",
            "Chunian",
            "Dajkot",
            "Daska",
            "Davispur",
            "Darya Khan",
            "Dera Ghazi Khan",
            "Dera Ismail Khan",
            "Dhaular",
            "Dina",
            "Dinga",
            "Dhudial Chakwal",
            "Dipalpur",
            "Faisalabad",
            "Fateh Jang",
            "Ghakhar Mandi",
            "Ghotki",
            "Gojra",
            "Gujranwala",
            "Gujrat",
            "Gujar Khan",
            "Harappa",
            "Haripur",
            "Hafizabad",
            "Haroonabad",
            "Hasilpur",
            "Haveli Lakha",
            "Hyderabad",
            "Islamabad",
            "Jalalpur Jattan",
            "Jampur",
            "Jaranwala",
            "Jhang",
            "Jhelum",
            "Jauharabad",
            "Kallar Syedan",
            "Kalabagh",
            "Karor Lal Esan",
            "Karachi",
            "Karak",
            "Kasur",
            "Kamalia",
            "Kāmoke",
            "Khanewal",
            "Khanpur",
            "Khairpur",
            "Khanqah Sharif",
            "Kharian",
            "Khushab",
            "Kot Adu",
            "Lahore",
            "Lakki Marwat",
            "Lalamusa",
            "Layyah",
            "Lawa Chakwal",
            "Liaquat Pur",
            "Lodhran",
            "Malakwal",
            "Mamoori",
            "Mailsi",
            "Mandi Bahauddin",
            "Mian Channu",
            "Mianwali",
            "Miani",
            "Multan",
            "Murree",
            "Muridke",
            "Mianwali Bangla",
            "Muzaffargarh",
            "Narowal",
            "Nankana Sahib",
            "Okara",
            "Pakpattan",
            "Pattoki",
            "Pindi Bhattian",
            "Pind Dadan Khan",
            "Pir Mahal",
            "Poonch",
            "Qaimpur",
            "Qila Didar Singh",
            "Raiwind",
            "Rajanpur",
            "Rahim Yar Khan",
            "Rawalakot",
            "Rawalpindi",
            "Renala Khurd",
            "Sadiqabad",
            "Sagri",
            "Sahiwal",
            "Sambrial",
            "Samundri",
            "Sangla Hill",
            "Sanghar",
            "Sarai Alamgir",
            "Sargodha",
            "Shakargarh",
            "Sheikhupura",
            "Shujaabad",
            "Sialkot",
            "Sohawa",
            "Soianwala",
            "Siranwali",
            "Tandlianwala",
            "Tank",
            "Talagang",
            "Taxila",
            "Toba Tek Singh",
            "Vehari",
            "Wah Cantonment",
            "Wazirabad",
            "Waziristan",
            "Yazman",
            "Zafarwal"};

    private static final String[] STATES = {
            "AJK",
            "Balochistan",
            "Gilgit Baltistan",
            "Kashmir",
            "KPK",
            "Punjab",
            "Sindh"
    };

    public static String[] getCities() {
        return CITIES;
    }

    public static String[] getStates() {
        return STATES;
    }
}
